'use client';
import { useQuery } from '@tanstack/react-query';
import * as React from 'react';
import { ForecastChart } from '@/components/charts';
import { StatusBadge } from '@/components/status-badge';
import { Empty, PageHeader, Panel, Skeleton } from '@/components/ui/misc';
import { Select } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { api } from '@/lib/api';
import { fmtDate, fmtMoney, fmtNum, humanize } from '@/lib/utils';

export default function Analytics() {
  const { data: a, isLoading } = useQuery({ queryKey: ['/analytics'], queryFn: () => api<any>('/analytics') });
  const [sel, setSel] = React.useState('');
  if (isLoading || !a) return <Skeleton className="h-96" />;
  const m = a.materials.find((x: any) => x.rawMaterialId === sel) ?? a.materials[0];
  const T = ({ heads, children }: { heads: string[]; children: React.ReactNode }) => <div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/60 text-left text-xs text-muted-foreground"><tr>{heads.map((h, i) => <th key={h} className={`whitespace-nowrap px-3 py-2 font-semibold ${i > 1 ? 'text-right' : ''}`}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>;
  return (
    <>
      <PageHeader title="Forecasts & predictive analytics" description="Trend-based consumption forecasts, safety-stock reorder levels, production requirements, expiry risk and supplier scoring. Every figure is computed from your own ledger — no black box." />
      <div className="mb-5 grid grid-cols-2 divide-x rounded-lg border bg-card sm:grid-cols-4">{([['Materials to order now', a.totals.orderNow, a.totals.orderNow ? 'text-danger' : ''], ['Materials short for open work orders', a.totals.shortfalls, a.totals.shortfalls ? 'text-warning' : ''], ['Value at expiry risk', fmtMoney(a.totals.valueAtRisk), a.totals.valueAtRisk ? 'text-warning' : ''], ['Suppliers at high risk', a.suppliers.filter((s: any) => s.risk === 'HIGH').length, '']] as const).map(([k, v, c]) => <div key={k} className="px-4 py-3"><div className="text-xs text-muted-foreground">{k}</div><div className={`num mt-0.5 text-2xl font-semibold ${c}`}>{v}</div></div>)}</div>
      <Tabs defaultValue="cons"><TabsList><TabsTrigger value="cons">Consumption forecast</TabsTrigger><TabsTrigger value="reorder">Reorder levels</TabsTrigger><TabsTrigger value="needs">Production needs</TabsTrigger><TabsTrigger value="risk">Expiry risk</TabsTrigger><TabsTrigger value="sup">Supplier performance</TabsTrigger></TabsList>
        <TabsContent value="cons">{m ? <Panel title="Monthly consumption" action={<Select className="w-64" value={m.rawMaterialId} onChange={(e) => setSel(e.target.value)} aria-label="Material">{a.materials.map((x: any) => <option key={x.rawMaterialId} value={x.rawMaterialId}>{x.code} · {x.name}</option>)}</Select>}>
          <ForecastChart history={m.history} forecast={m.forecast} uom={m.uom} />
          <div className="mt-3 grid grid-cols-2 gap-4 text-sm sm:grid-cols-4"><div><div className="text-xs text-muted-foreground">On hand</div><div className="num font-medium">{fmtNum(m.onHand, 1)} {m.uom}</div></div><div><div className="text-xs text-muted-foreground">Days of cover</div><div className="num font-medium">{m.daysOfCover ?? '—'}</div></div><div><div className="text-xs text-muted-foreground">Supplier lead time</div><div className="num font-medium">{m.leadTimeDays} days</div></div><div><div className="text-xs text-muted-foreground">Next month (forecast)</div><div className="num font-medium">{fmtNum(m.forecast[0]?.qty, 1)} {m.uom}</div></div></div></Panel> : <Empty title="No consumption history yet" hint="Forecasts appear after batches have consumed material." />}</TabsContent>
        <TabsContent value="reorder"><Panel flush><T heads={['Material', 'Action', 'On hand', 'Current reorder', 'Recommended', 'Safety stock', 'Lead time (d)']}>{a.materials.map((x: any) => <tr key={x.rawMaterialId} className="border-t"><td className="px-3 py-2"><span className="id-text mr-2 text-muted-foreground">{x.code}</span>{x.name}</td><td className="px-3 py-2 text-right"><StatusBadge status={x.action === 'ORDER_NOW' ? 'CRITICAL' : x.action === 'REVISE_REORDER_LEVEL' ? 'WARNING' : 'OK'} /></td><td className="px-3 py-2 text-right num">{fmtNum(x.onHand, 1)}</td><td className="px-3 py-2 text-right num">{fmtNum(x.currentReorderLevel, 1)}</td><td className="px-3 py-2 text-right num font-medium">{fmtNum(x.recommendedReorderLevel, 1)}</td><td className="px-3 py-2 text-right num text-muted-foreground">{fmtNum(x.safetyStock, 1)}</td><td className="px-3 py-2 text-right num text-muted-foreground">{x.leadTimeDays}</td></tr>)}</T><p className="border-t px-3 py-2 text-xs text-muted-foreground">Recommended = average daily demand × lead time + 95%-service safety stock (1.65 · σ<sub>daily</sub> · √lead time).</p></Panel></TabsContent>
        <TabsContent value="needs"><Panel flush title={`Open work orders: ${a.productionNeeds.openWorkOrders}`}><T heads={['Material', 'UOM', 'Required', 'On hand', 'On order', 'Shortfall']}>{a.productionNeeds.materials.map((x: any) => <tr key={x.code} className="border-t"><td className="px-3 py-2"><span className="id-text mr-2 text-muted-foreground">{x.code}</span>{x.name}</td><td className="px-3 py-2 text-right text-muted-foreground">{x.uom}</td><td className="px-3 py-2 text-right num">{fmtNum(x.required, 1)}</td><td className="px-3 py-2 text-right num">{fmtNum(x.onHand, 1)}</td><td className="px-3 py-2 text-right num">{fmtNum(x.onOrder, 1)}</td><td className={`px-3 py-2 text-right num ${x.shortfall > 0 ? 'font-semibold text-danger' : 'text-muted-foreground'}`}>{x.shortfall > 0 ? fmtNum(x.shortfall, 1) : '—'}</td></tr>)}{!a.productionNeeds.materials.length && <tr><td colSpan={6}><Empty title="No open work orders" /></td></tr>}</T></Panel></TabsContent>
        <TabsContent value="risk"><Panel flush><T heads={['Material', 'Lot', 'Expiry', 'Days left', 'On hand', 'Projected unused', 'Value at risk']}>{a.expiryRisk.map((x: any) => <tr key={x.lotId} className="border-t"><td className="px-3 py-2">{x.material}</td><td className="px-3 py-2 text-right id-text">{x.lotNumber}</td><td className="px-3 py-2 text-right num">{fmtDate(x.expiryDate)}</td><td className="px-3 py-2 text-right num">{x.daysLeft}</td><td className="px-3 py-2 text-right num">{fmtNum(x.onHand, 1)} {x.uom}</td><td className="px-3 py-2 text-right num text-warning">{fmtNum(x.projectedUnused, 1)} ({x.riskPct}%)</td><td className="px-3 py-2 text-right num font-medium">{fmtMoney(x.valueAtRisk)}</td></tr>)}{!a.expiryRisk.length && <tr><td colSpan={7}><Empty title="No lots at risk" hint="At current burn rate every approved lot is consumed before it expires." /></td></tr>}</T><p className="border-t px-3 py-2 text-xs text-muted-foreground">FEFO simulation using the last 6 months’ average daily consumption.</p></Panel></TabsContent>
        <TabsContent value="sup"><Panel flush><T heads={['Supplier', 'Grade', 'Score', 'On-time', 'Fill rate', 'Quality', 'Price stability', 'Risk']}>{a.suppliers.map((s: any) => <tr key={s.supplierId} className="border-t"><td className="px-3 py-2">{s.name}<div className="text-xs text-muted-foreground">{s.deliveries} deliveries</div></td><td className="px-3 py-2 text-right font-semibold">{s.grade}</td><td className="px-3 py-2 text-right num">{s.score ?? '—'}</td>{[s.onTimePct, s.fillRatePct, s.qualityPct, s.priceStabilityPct].map((v, i) => <td key={i} className="px-3 py-2 text-right num">{v != null ? `${v}%` : '—'}</td>)}<td className="px-3 py-2 text-right"><StatusBadge status={s.risk} /></td></tr>)}</T><p className="border-t px-3 py-2 text-xs text-muted-foreground">Score weights: on-time 35%, quality 30%, fill rate 20%, price stability 15%. Missing components are re-weighted.</p></Panel></TabsContent>
      </Tabs>
    </>
  );
}
